# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: '**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Install NPM Package
        run: npm ci

      - name: Setup Logins
        run: bash login.sh

      - name: Clone Scripts
        run: bash deploy.sh
